// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhejC3YmIcFSvEUDVTebvnAMX10mrCn8',
    appId: '1:777604857527:web:02cdda8f68781374d21732',
    messagingSenderId: '777604857527',
    projectId: 'newagent-3bd04',
    authDomain: 'newagent-3bd04.firebaseapp.com',
    databaseURL: 'https://newagent-3bd04.firebaseio.com',
    storageBucket: 'newagent-3bd04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJru13brgF1bLQfPqWMr3v8lVcAU4Q3E',
    appId: '1:777604857527:android:0bb314b3f7b0a768d21732',
    messagingSenderId: '777604857527',
    projectId: 'newagent-3bd04',
    databaseURL: 'https://newagent-3bd04.firebaseio.com',
    storageBucket: 'newagent-3bd04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBTLV2gsk0pqJX5bq34nzP082s9BDBsM',
    appId: '1:777604857527:ios:2fa55e47ecbe28f1d21732',
    messagingSenderId: '777604857527',
    projectId: 'newagent-3bd04',
    databaseURL: 'https://newagent-3bd04.firebaseio.com',
    storageBucket: 'newagent-3bd04.appspot.com',
    iosClientId: '777604857527-1lpegkrnkkecl8fthas6dmiv2uqlqq2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBTLV2gsk0pqJX5bq34nzP082s9BDBsM',
    appId: '1:777604857527:ios:2fa55e47ecbe28f1d21732',
    messagingSenderId: '777604857527',
    projectId: 'newagent-3bd04',
    databaseURL: 'https://newagent-3bd04.firebaseio.com',
    storageBucket: 'newagent-3bd04.appspot.com',
    iosClientId: '777604857527-1lpegkrnkkecl8fthas6dmiv2uqlqq2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeJournal',
  );
}
